### ISSUE TITLE
Widget does not appear

### ISSUE THREAD

**Issue by MrHappy** [stefano-m/awesome-capslock_widget#1]
First of... I was looking for something like this, cause my laptop has no indicator for numlock and a barely visible one for capslock..
I think I copied and pasted the right things on the right places, but 
```
      layout = wibox.layout.fixed.horizontal,
      -- CapsLock
      capslock.key
```
gives me an error. Removing .key makes the error go away.
But the A/a do not show.
Am I missing something??

**Comment by stefano-m** [comment]
Hi, I'm afraid I'd need more information to be able to help you.

- what version of Awesome are you using (this widget works with Awesome 4.x)
- what is exactly the error that you are getting?
- how have you configured the widget? Can you post the relevant part of your `rc.lua`?

Thanks!

**Comment by MrHappy** [comment]
Hi,

- Awesome v4.3

The error I get (twice above each other) is
`error global.lua, attempt to index a nil value (global 'capslock')`

In rc.lua I added (in the same folder I added capslock.lua)
`local capslock = require("capslock")`
In layout/top-panel.lua I added both lines with 'capslock'
```
      layout = wibox.layout.fixed.horizontal,
      -- CapsLock
      capslock,
      -- Clock
```
In configuration/keys/global.lua I added the line with 'capslock'
```
  globalKeys =
    awful.util.table.join(
    capslock.key,
    globalKeys,
```
When I pasted everyting in rc.lua it didn work, so I searched the lua-files that had lines like you described and added them there.
Worth mentioning is that my awesome is not a stock configuration.. ;)

**Comment by stefano-m** [comment]
Hi and thanks for the extra information.

```
error global.lua, attempt to index a nil value (global 'capslock')
```

means that awesome does not find the module, so I would guess that for some reason it has either not been installed or imported correctly.

I see that you have your configuration split among a couple of files `layout/top-panel.lua` and `configuration/keys/global.lua`: you need to ensure that `capslock` is `require`d there; if you require it in `rc.lua` only, it won't work, that's why you get two errors (one per file).

I don't know how your files are laid out, but you need to ensure that the same module is exposed to both.

Hope this helps.

**Comment by MrHappy** [comment]
Awesome.. It works now! Thanks!
